version: '3'
services:
  identity:
    image: litgraph-identity-server
    build: ./Litgraph.IdentityServer
    container_name: litgraph-identity-server
    depends_on:
      - identity-db
    env_file: identity.env
    networks:
      - identity-service-network
      - main-network
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - $HOME\.aspnet\https:/https/
      
  identity-db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "identity-db"
    env_file: identity-db.env
    networks:
      - identity-service-network
    ports:
      - "1433:1433"
    volumes:
      - $HOME\sql-server:/var/opt/mssql
  
  graph-db:
    image: "neo4j"
    container_name: "graph-db"
    env_file: graph-db.env
    networks:
      - main-network
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME\neo4j:/data


networks:
  identity-service-network:
  main-network: